### ISSUE TITLE
The script doesn't work

### ISSUE THREAD

**Issue by Marton252** [1MDen/infinite-craft-automatic-python#1]
this is the error:

Traceback (most recent call last):
  File "C:\Users\Marton\Downloads\main.py", line 12, in <module>
    sidebar = driver.find_element(By.CLASS_NAME, "mobile-items")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marton\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marton\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Marton\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".mobile-items"}

**Comment by MDen-MT** [comment]
The site has been changed and many of the class names have been changed so the script no longer works. For now I have no interest in rewriting it. Sorry.
